nodeLinker: node-modules
enableGlobalCache: false
nodeVersion: "20.x"
packageExtensions:
  "@reown/appkit-siwx@*":
    peerDependencies:
      lit: "3.3.0"
  "@solana/wallet-adapter-particle@*":
    peerDependencies:
      bs58: "^4.0.1"
  "@keystonehq/sol-keyring@*":
    peerDependencies:
      react: "18.3.1"
      react-dom: "18.3.1"
  "react-qr-reader@*":
    peerDependencies:
      react: "18.3.1"
      react-dom: "18.3.1"
  "qrcode.react@*":
    peerDependencies:
      react: "18.3.1"