nodeLinker: node-modules
enableGlobalCache: false
nodeVersion: "20.x"
enableScripts: true
enableTelemetry: false
# Make CI tolerant to peer mismatches and immutable installs in Kaniko
enableStrictPeerDependencies: false
enableImmutableInstalls: false