nodeLinker: node-modules
enableGlobalCache: false
nodeVersion: "20.x"
enableScripts: true
enableTelemetry: false
enableStrictPeerDependencies: false
enableImmutableInstalls: false
enableWorkspaces: false
workspaceFolder: false
enableWorkspaceReassignment: false
logLevel: error

# Completely disable workspace features
enableInteractiveMode: false