export const PaymentIntentStatus = Object.freeze({
  CREATED: 'CREATED',
  SENT: 'SENT',
  CONFIRMED: 'CONFIRMED',
  CONSUMED: 'CONSUMED',
  EXPIRED: 'EXPIRED',
  MISMATCH: 'MISMATCH'
});

export const DEFAULT_JOIN_TICKET_TTL_SECONDS = 90;
export const MIN_JOIN_TICKET_TTL_SECONDS = 60;
export const MAX_JOIN_TICKET_TTL_SECONDS = 120;
